Revert "Revert "feat: switch to sqlite to simplify things""
This reverts commit e445cafb2e94cc26b12975414dea7c0f2057e502.

diff --git a/docker/8.0/start-container b/docker/8.0/start-container
--- a/docker/8.0/start-container
+++ b/docker/8.0/start-container
@@ -15,15 +15,11 @@ chmod -R ugo+rw /.composer
 . /var/www/html/.env
 if [ "" == "${APP_KEY}" ]; then
     gosu $WWWUSER /usr/bin/composer install --working-dir=/var/www/html
-    for i in $(seq 1 10); do
-        echo "######## ...waiting for database"
-        sleep 5
-        /usr/bin/php /var/www/html/artisan migrate
-        SUCCESS=$?
-        [ $SUCCESS -eq 0 ] && break
-    done
+    gosu $WWWUSER touch /var/www/html/database/database.sqlite
+    /usr/bin/php /var/www/html/artisan migrate
+    SUCCESS=$?
     if [ $SUCCESS -gt 0 ]; then
-        echo "######## to many database errors... giving up"
+        echo "######## database error... giving up"
         exit 1
     fi 
     /usr/bin/php /var/www/html/artisan key:generate
